### ISSUE TITLE
ImportError: Plugin gstoverlayopencv not registered

### ISSUE THREAD

**Issue by balajiraghuram92** [jackersson/gst-overlay#1]
When executing the code,gettting the following error:
Note:no code changes,GStreamer - 1.15.1, Opencv-python is installed
(python3:11020): GStreamer-WARNING **: Element factory metadata for 'gstoverlayopencv' has no valid long-name field
Traceback (most recent call last):
  File "run.py", line 19, in <module>
    from gst_overlay.gst_overlay_opencv import GstOverlayOpenCv
  File "/work/mediaPlayer(Gstreamer)/gst-overlay/gst_overlay/gst_overlay_opencv.py", line 93, in <module>
    register_by_name(GST_OVERLAY_OPENCV)
  File "/work/mediaPlayer(Gstreamer)/gst-overlay/gst_overlay/gst_overlay_opencv.py", line 90, in register_by_name
    raise ImportError("Plugin {} not registered".format(plugin_name)) 
ImportError: Plugin gstoverlayopencv not registered

**Comment by jackersson** [comment]
Hi, 

Can you print out of next command?: 
`gst-inspect-1.0 --version`

Also I just cloned it to my PC and run next commands: 
`python3 run.py -f car.mpg -i attachments/cat -c`

Produces next gstreamer pipeline: 
`gst-launch-1.0 filesrc location=car.mpg ! decodebin ! videoconvert ! gstoverlaycairo name=overlay ! videoconvert ! gtksink sync=false`

And: 
`python3 run.py -f car.mpg -i attachments/cat -o`

Produces:
`gst-launch-1.0 filesrc location=car.mpg ! decodebin ! videoconvert ! gstoverlayopencv name=overlay ! videoconvert ! gtksink sync=false`

Also check Gstreamer version (https://gstreamer.freedesktop.org/releases/1.14/#1.14.2). Latest is 14.2, but you have 1.15.1.

**Comment by balajiraghuram92** [comment]
I am chechking the version using gst-inspect-1.0 --version and i am getting 1.15.0
Which ubuntu version you are using 18.04 or 16.04?

**Comment by jackersson** [comment]
16.04

I have an repository with simple plugin to run (https://github.com/jackersson/gst-python-plugins)
Just follow instructions in README. 

P. S. - previous is from official supported examples, so it should work. In case of error - send me debug info.

**Comment by jackersson** [comment]
Hi, 

Any updates on your problem? 

Answers to your questions: 
Do we have to run the python program, if i run it getting following error?
$python gstplugin_py.py

- No, just export GST_PLUGIN_PATH=... As gst-python has script for loading python plugins from files in GST_PLUGIN_PATH ([here](https://github.com/GStreamer/gst-python/blob/master/plugin/gstpythonplugin.c))

Did you try the same thing or are you using a installer of gstreamer 1.14?
- I tried on Ubuntu 18, 16, with Gstreamers 1.14-15 and if you installed everything right than this code should work.

Check installation [guide](http://lifestyletransfer.com/how-to-install-gstreamer-from-sources-on-ubuntu/), especially [part with gst-python](https://gist.github.com/jackersson/9d3b0c578c1e625b6b79ea04e2cebd15#file-build-gstreamer-sh) 

Hope everything works)

**Comment by jefflgaol** [comment]
I solved this problem by installing these (Python 3):
```
sudo apt-get update 
sudo apt-get install python3-gst-1.0
sudo apt-get install python3-gst-1.0-dbg (if necessary)
```
